import React, { useState, useRef } from 'react';

// === 1. 核心数据源：年度累计 (1957-2025) ===
const KEY_EVENTS = [
  { year: 1957, val: 1, event: "Sputnik 1 发射" },
  { year: 1961, val: 300, event: "首次卫星解体" },
  { year: 1970, val: 2000, event: "太空竞赛高峰" },
  { year: 1980, val: 4600, event: "航天常态化" },
  { year: 1990, val: 7500, event: "老旧卫星积累" },
  { year: 2000, val: 9100, event: "ISS 时代" },
  { year: 2007, val: 12500, event: "反卫星测试(CN)" },
  { year: 2009, val: 14200, event: "Iridium 碰撞" },
  { year: 2015, val: 17800, event: "商业航天起步" },
  { year: 2021, val: 23000, event: "反卫星测试(RU)" },
  { year: 2024, val: 39200, event: "星链爆发" },
  { year: 2025, val: 43500, event: "LEO 拥堵" }
];

const generateYearlyData = () => {
  let fullData = [];
  for (let i = 0; i < KEY_EVENTS.length - 1; i++) {
    const start = KEY_EVENTS[i];
    const end = KEY_EVENTS[i+1];
    const steps = end.year - start.year;
    fullData.push({ year: start.year, val: start.val, event: start.event });
    for (let j = 1; j < steps; j++) {
      const currYear = start.year + j;
      const currVal = Math.round(start.val + (end.val - start.val) * (j / steps));
      fullData.push({ year: currYear, val: currVal, event: null });
    }
  }
  const last = KEY_EVENTS[KEY_EVENTS.length - 1];
  fullData.push({ year: last.year, val: last.val, event: last.event });
  return fullData;
};
const YEARLY_DATA = generateYearlyData();

// === 2. 国家数据 ===
const COUNTRY_DATA = [
  { name: 'USA', count: 25786, color: '#fff' },
  { name: 'RUSSIA', count: 25144, color: '#FF6B00' },
  { name: 'CHINA', count: 8774, color: '#5456F0' },
  { name: 'FRANCE', count: 1471, color: '#999' },
  { name: 'INDIA', count: 758, color: '#666' }
];

export default function DataPanel() {
  const [hoverData, setHoverData] = useState(null);

  return (
    <div style={{
      width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif', color: '#fff'
    }}>
      
      {/* 🔴【控制点 1】：这里控制 4 个板块的总大小 */}
      <div style={{
        // 1. 宽度控制：可以使用百分比 (85vw) 或 像素 (1200px)
        width: '85vw', 
        maxWidth: '1200px', 
        
        // 2. 比例/高度控制：
        // 方案A：锁定比例 (推荐) -> 改这个 '3 / 2' 可以变扁或变方
        aspectRatio: '3 / 2', 
        // 方案B：锁定高度 (如果不想用比例) -> 删除 aspectRatio，打开 height
        // height: '800px', 

        display: 'grid', 
        gridTemplateColumns: '1fr 1fr', 
        gridTemplateRows: '1fr 1fr',    
        gap: '24px', 
        boxSizing: 'border-box'
      }}>
        
        {/* === 板块 1: 趋势图 (左上) === */}
        <div style={cardStyle}>
          <div style={headerStyle}>
            <div style={dotStyle('#FF6B00')}></div>
            <div>
              <h3 style={titleStyle}>太空垃圾数量趋势</h3>
              <p style={subTitleStyle}>TREND OF YEARLY SPACE DEBRIS</p>
            </div>
          </div>
          
          <div style={{ flex: 1, position: 'relative', width: '100%', minHeight: 0, display:'flex', flexDirection:'column' }}>
             
             {/* 🔴【控制点 2】：这里单独控制曲线图的大小 */}
             <div style={{ 
                 flex: 1,               // 默认充满剩余空间
                 width: '100%',         // 宽度：通常是 100%
                 
                 // 如果你想强制压缩高度，可以在这里加 padding 或 height
                 // height: '200px', 
                 // marginTop: '20px', 
                 
                 position: 'relative' 
             }}>
                <SmoothLineChart data={YEARLY_DATA} hoverData={hoverData} setHoverData={setHoverData} />
                
                {/* Tooltip */}
                {hoverData && (
                  <div style={tooltipStyle(hoverData.x, hoverData.y - 15)}>
                    <div style={{ fontWeight: 'bold', fontSize:'0.9rem' }}>{hoverData.year}</div>
                    <div style={{ color: '#FF6B00', fontSize:'0.8rem' }}>{hoverData.val.toLocaleString()} <span style={{fontSize:'0.6rem', color:'#888'}}>TOTAL</span></div>
                    {hoverData.event && <div style={{fontSize:'0.6rem', color:'#ccc', borderTop:'1px solid #444', marginTop:'2px', paddingTop:'2px'}}>{hoverData.event}</div>}
                  </div>
                )}
             </div>
          </div>
        </div>

        {/* === 板块 2: 国家数据 (右上) === */}
        <div style={cardStyle}>
           <div style={headerStyle}>
            <div style={dotStyle('#fff')}></div>
            <div>
              <h3 style={titleStyle}>国家产生垃圾数</h3>
              <p style={subTitleStyle}>DEBRIS GENERATED BY COUNTRIES</p>
            </div>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-evenly', flex: 1, padding: '10px 0' }}>
              {COUNTRY_DATA.map((item, idx) => (
                <BarRow key={idx} label={item.name} count={item.count} max={30000} color={item.color} />
              ))}
          </div>
        </div>

        {/* === 板块 3: 碎片来源 (左下) === */}
        <div style={cardStyle}>
          <div style={headerStyle}>
            <div style={dotStyle('#5456F0')}></div>
            <div>
              <h3 style={titleStyle}>碎片来源</h3>
              <p style={subTitleStyle}>SOURCE AND SIZE OF FRAGMENTS</p>
            </div>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flex: 1, padding: '0 20px' }}>
              <HexagonStat val="1.3亿" label="< 1cm" color="#5456F0" scale={0.9} shape="poly1" />
              <HexagonStat val="100万" label="1-10cm" color="#FF6B00" scale={1} shape="poly2" />
              <HexagonStat val="3.6万" label="> 10cm" color="#fff" scale={1.1} shape="poly3" />
          </div>
        </div>

        {/* === 板块 4: 碎片数据 (右下) === */}
        <div style={cardStyle}>
          <div style={headerStyle}>
            <div style={dotStyle('#FF0000')}></div>
            <div>
              <h3 style={titleStyle}>碎片数据</h3>
              <p style={subTitleStyle}>DEBRIS GENERATED BY COUNTRIES</p>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flex: 1, padding: '0 20px' }}>
              <div style={{ textAlign: 'left' }}>
                  <div style={{ fontSize: '3.5rem', fontWeight: '900', color: '#fff' }}>1.3亿</div>
                  <div style={{ fontSize: '0.8rem', color: '#888', marginTop: '5px' }}>微小碎片总量</div>
              </div>
              <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '3.5rem', fontWeight: '900', color: '#fff' }}>7.5<span style={{fontSize:'1.5rem'}}>km/s</span></div>
                  <div style={{ fontSize: '0.8rem', color: '#888', marginTop: '5px' }}>平均撞击速度</div>
              </div>
          </div>
          <div style={{ width: '100%', height: '12px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', marginTop: 'auto' }}></div>
        </div>

      </div>
    </div>
  );
}

// === 组件：平滑曲线图 ===
const SmoothLineChart = ({ data, hoverData, setHoverData }) => {
  const containerRef = useRef(null);
  
  const handleMouseMove = (e) => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const x = e.clientX - rect.left; 
    const width = rect.width;
    if (x < 0 || x > width) return;
    const index = Math.round((x / width) * (data.length - 1));
    const d = data[index];
    
    const yPercent = getY(d.val); 
    const pxY = (yPercent / 100) * rect.height;
    if (d) setHoverData({ x: (index / (data.length - 1)) * width, y: pxY, year: d.year, val: d.val, event: d.event });
  };

  // 🔴【控制点 3】：控制曲线的高度占比
  // 当前：100 - (val / 45000) * 80
  // * 80 表示最高点只占容器高度的 80% (留出 20% 顶部呼吸空间)
  // 如果想更扁，把 80 改小 (例如 60)
  // 如果想更满，把 80 改大 (例如 95)
  const getY = (val) => 100 - (val / 45000) * 80; 

  const pointsStr = data.map((d, i) => `${(i / (data.length - 1)) * 100},${getY(d.val)}`).join(' ');
  const pathD = `M ${pointsStr}`;

  return (
    <div 
      ref={containerRef}
      style={{ width: '100%', height: '100%', cursor: 'crosshair' }}
      onMouseMove={handleMouseMove}
      onMouseLeave={() => setHoverData(null)}
    >
      <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none" style={{ overflow: 'visible' }}>
        <defs>
          <linearGradient id="gradOrange" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stopColor="#FF6B00" stopOpacity="0.4" />
            <stop offset="100%" stopColor="transparent" stopOpacity="0" />
          </linearGradient>
        </defs>
        
        <line x1="0" y1={getY(20000)} x2="100" y2={getY(20000)} stroke="#333" strokeWidth="0.5" strokeDasharray="2" />
        <line x1="0" y1={getY(40000)} x2="100" y2={getY(40000)} stroke="#333" strokeWidth="0.5" strokeDasharray="2" />

        <path d={`${pathD} L 100,100 L 0,100 Z`} fill="url(#gradOrange)" />
        <path d={pathD} fill="none" stroke="#FF6B00" strokeWidth="2" vectorEffect="non-scaling-stroke" />
        
        {hoverData && (
           <line x1={(data.findIndex(d => d.year === hoverData.year) / (data.length - 1)) * 100} y1="0" x2={(data.findIndex(d => d.year === hoverData.year) / (data.length - 1)) * 100} y2="100" stroke="rgba(255,255,255,0.3)" strokeWidth="1" vectorEffect="non-scaling-stroke" />
        )}
        {hoverData && (
            <circle cx={(data.findIndex(d => d.year === hoverData.year) / (data.length - 1)) * 100} cy={getY(hoverData.val)} r="2" fill="#fff" stroke="#FF6B00" strokeWidth="1" vectorEffect="non-scaling-stroke" />
        )}
      </svg>
      <div style={{ position: 'absolute', bottom: 0, width: '100%', display: 'flex', justifyContent: 'space-between', fontSize: '0.6rem', color: '#666' }}>
          <span>1957</span>
          <span>2025</span>
      </div>
    </div>
  );
};

// === 样式与辅助组件 ===

const tooltipStyle = (left, topOffset) => ({
  position: 'absolute', left: left, top: topOffset,
  transform: 'translate(-50%, -50%)',
  background: 'rgba(20, 20, 20, 0.95)', padding: '6px 10px', borderRadius: '4px',
  border: '1px solid rgba(255, 107, 0, 0.3)', pointerEvents: 'none', zIndex: 20,
  minWidth: '100px', textAlign: 'center', boxShadow: '0 4px 10px rgba(0,0,0,0.5)',
  whiteSpace: 'nowrap'
});

const BarRow = ({ label, count, max, color }) => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
        <div style={{ width: '100%', height: '14px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', position: 'relative' }}>
            <div style={{ width: `${Math.min((count/max)*100, 100)}%`, height: '100%', background: color, borderRadius: '2px' }}></div>
            <div style={{ position: 'absolute', left: '5px', top: '50%', transform: 'translateY(-50%)', fontSize: '0.7rem', color: '#fff', textShadow: '0 0 2px #000', fontWeight: 'bold', pointerEvents: 'none' }}>
                {label}
            </div>
             <div style={{ position: 'absolute', right: '5px', top: '50%', transform: 'translateY(-50%)', fontSize: '0.7rem', color: '#fff', textShadow: '0 0 2px #000', fontFamily: 'monospace' }}>
                {count.toLocaleString()}
            </div>
        </div>
    </div>
);

const HexagonStat = ({ val, label, color, scale, shape }) => {
    const clipPath = shape === 'poly1' 
        ? 'polygon(20% 0%, 80% 0%, 100% 100%, 0% 100%)' 
        : shape === 'poly2' 
        ? 'polygon(0% 20%, 100% 0%, 100% 80%, 0% 100%)' 
        : 'polygon(10% 0, 90% 0, 100% 50%, 90% 100%, 10% 100%, 0 50%)';

    return (
      <div style={{ transform: `scale(${scale})`, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <div style={{ 
              width: '80px', height: '60px', 
              background: `rgba(255,255,255,0.1)`,
              border: `1px solid ${color}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              clipPath: clipPath,
              marginBottom: '10px'
          }}>
              <div style={{ width: '40%', height: '40%', background: color, opacity: 0.8, clipPath: clipPath }}></div>
          </div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: '#fff' }}>{val}</div>
          <div style={{ fontSize: '0.8rem', color: '#888' }}>{label}</div>
      </div>
    );
};

const cardStyle = {
    background: 'rgba(30, 30, 30, 0.9)', 
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '8px', 
    padding: '24px', 
    display: 'flex', flexDirection: 'column',
    boxShadow: '0 10px 40px rgba(0,0,0,0.6)',
};
const headerStyle = { display: 'flex', gap: '10px', marginBottom: '15px', alignItems: 'center' };
const titleStyle = { margin: 0, fontSize: '0.9rem', fontWeight: 'bold', letterSpacing: '0.5px', color: '#fff', textTransform: 'uppercase' };
const subTitleStyle = { margin: 0, fontSize: '0.55rem', color: '#888', letterSpacing: '1px', textTransform: 'uppercase' };
const dotStyle = (color) => ({ width: '8px', height: '8px', borderRadius: '50%', background: color, boxShadow: `0 0 10px ${color}` });